### ISSUE TITLE
Update to PyTorch 0.4.1

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#1267]
- [ ] #1294 Fix failing CPU tests (@neerajprad, @fritzo)
    - [x] Update .travis.yml
    - [x] Work around https://github.com/pytorch/pytorch/issues/9917 bug in `torch.bernoulli(p.expand(s))`
    - [x] Work around https://github.com/pytorch/pytorch/issues/9521 bug in `Dirichlet` of expanded tensors
    - [x] Work around https://github.com/pytorch/pytorch/issues/9977 `RuntimeError` in `test_em.py` (@fritzo)
    - [ ] Work around https://github.com/pytorch/pytorch/issues/10241 broken `log`, `exp`
- [x] #1271 Use `Independent` rather than `ReshapedDistribution` (@alicanb)
- [x] #1273 Clamp to nonnegative before `.sqrt()` in  `newton_step_2d()`
- [x] #1274 Use `torch.logsumexp` when available
- [x] #1276 Update `pyro.ops.jit` (@eb8680, @fritzo)
- [x] #1268 Wrap all new distributions in pyro/distributions/torch.py (@fritzo)
- [x] Fix failing GPU tests (@neerajprad , @jpchen )
- [ ] Update docker files (@neerajprad)
- [ ] Cut a Pyro release 0.2.2 (@fritzo, @jpchen)

**Comment by neerajprad** [comment]
I will start with the tests / breaking code on `dev` and update `.travis.yml`. We can cover the remaining tasks in parallel.

**Comment by fritzo** [comment]
Great, I'll start migrating our distributions in #1268. This will fail CI until we switch torch version on travis.

**Comment by alicanb** [comment]
I just merged #1264 into dev, don't forget to pull before pushing!

**Comment by eb8680** [comment]
Is `pyro.ops.jit.compile` deprecated/obsolete under PyTorch 0.4.1? Do we need to remove it?

**Comment by alicanb** [comment]
https://github.com/pytorch/pytorch/pull/10269 -> for expand bugs
