### ISSUE TITLE
Add one or more environment.yml or requirements.txt files

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#147]
The [`conda`](https://conda.io/docs/user-guide/install/index.html) package manager improves on `pip` by providing broader support for binary dependencies, which are common in areas of machine learning and GPU computation. Whereas `pip` uses a `requirements.txt`, `conda` prefers an `environment.yml`. The aim of this issue is to make it easier for `conda` users to install pyro.

## Tasks
- [ ] #148 Add an initial `environment.yml` for development
- [ ] Deduplicate requirements among `setup.py` and `environment.yml`
- [ ] Split out an `environment.dev.yml`, simplify `environment.yml` and add instructions in the `Installation` section of `README.md`
