### ISSUE TITLE
Renaming things before launch

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#159]
This issue is a laundry list of possible alternate names for things in Pyro.

## Distributions

- [x] #384 Rename `Distribution.support()` -> `.enumerate_support()`
- [x] #382 `DiagNormal`, `NormalChol` -> `Normal*`, and maybe even an explicit distinction between univariate Normal and multivariate Normal such as `Normal*` and `MultivariateNormal*`
- [x] Make sure param naming is uniform, eg in distributions
- [x] #182 Settle on internal variable name convention (see #167) 

## General

- [x] #387 Rename package for pypi (probably `pyro-ppl`) (see #150)
- [x] Revisit names for inference operations
- [x] `KL_QP.eval_grad` -> `.eval_surrogate_loss` (or change its behavior to return `loss.grad` (see #168)
- [x] combine the relevant kl_qp implementations
- [x] `KL_QP`/`ELBo` -> `Elbo` to spare Martin's fingers. ([pep8](https://stackoverflow.com/questions/2853531/how-do-you-pep-8-name-a-class-whose-name-is-an-acronym) recommends `Elbo`) (see #74)

## Triaged

- [ ] Rename `condition` to `observe` to clarify that it conditions on values instead of arbitrary propositions being true
- [ ] Remove `observe` as alias of `sample` (completes #29 )
- [ ] Greek names -> meaningful names (mu, sigma -> loc, scale) (should match `torch.distributions`)
- [ ] `log_pdf` -> `sum_log_prob`, `batch_log_pdf` -> `log_pdf` (to match `torch.distributions` api)
- [ ] Rename `LambdaPoutine` to something more evocative (`IndepPoutine`?), especially after #184 
- [ ] `map_data` -> `imap`/`map_iid` (`imap` is used in Python2's itertools library as a map iterator.)
- [ ] Rename `*Poutine` to `*Handler`...

(Edited to include everyone's ideas)
