### ISSUE TITLE
[FR] Conjugate operations on existing distributions

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#1723]
Exact variable elimination of continuous random variables requires a number of new distribution methods. Some of the mathematics for these is already implemented in [pyro.contrib.tracking](http://pyro.ai/examples/ekf.html). To make variable elimination algorithms generic, we should move this math into new methods of subclasses of `TorchDistribution` or new functions in `pyro.distributions.conjugate`.

Note this issue concerns only low-level distributions methods, not high-level inference algorithms. 

## Interface

This is WIP.

Univariate distributions can perform "Bayesian fusion" aka "filter update", equivalent to multiplying densities pointwise, i.e. adding log densities pointwise.
```py
def fuse(dist1, dist2):
    assert type(dist1) is type(dist2)
    # returns (log_prob, updated dist)
    # dispatch on type-type pairs, following kl_divergence()
```
Conjugate pairs can be conditioned on distribution-valued observations (see #988 )
```py
def observe(param_dist, obs_dist):
    # returns (log_prob, updated dist of type param_dist)
    # dispatch on type-type pairs
```
Multivariate distributions like `MultivariateNormal` can encode multiple univariate distributions. Maybe we can support these by allowing transforms?
```py
def transform_and_observe(param_dist, transform, obs_dist):
    # returns (log_prob, updated dist of type param_dist)
```

## Tasks:

- [ ] settle on interface
- [ ] implement methods for `Normal`
- [ ] implement methods for `Beta`
- [ ] implement methods for `Binomial`: `.as_posterior()`
- [ ] implement methods for `MultivariateNormal`
- [ ] implement methods for `Dirichlet`

**Comment by fritzo** [comment]
Closing in favor of [Funsor](https://github.com/pyro-ppl/funsor), which can be used in a number of ways:
- as a complete backend for pyro
- to implement custom Pyro distributions
- as a DSL within Pyro models, constructing factors via `pyro.factor` statements.
