### ISSUE TITLE
Pyro minor release 0.3.1

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/pyro#1737]
Task-list:
 - [x] Remove networks x from dependency. #1736 
 - [x] Update ~~setup.py and~~ .travis.yml to use PyTorch 1.0.1
 - [x] Fix CUDA tests.
 - [ ] Address issues for next release:
   - [x] Progress bar fixes in mcmc: https://github.com/pyro-ppl/pyro/issues/1728
   - [ ] ~Abstract infer classes lazily consume traces: https://github.com/pyro-ppl/pyro/issues/1725. (not a blocker)~
   - [ ] ~Sample from collapsed latent variables in conjugate distributions. (not a blocker)~
   - Any other?

Please feel free to add to the list if we think there are certain fixes (or features, though prioritizing on fixes) that should make it into this release.

**Comment by eb8680** [comment]
Are there any other easy performance wins along the lines of #1736 we could include?

**Comment by fritzo** [comment]
I suggest we update travis to use PyTorch 1.0.1 but keep setup.py permissive via `torch>=1.0`, since Pyro doesn't require anything in the new PyTorch release.

**Comment by neerajprad** [comment]
> Are there any other easy performance wins along the lines of #1736 we could include?

I can't think of much at the moment. There's the issue of TracePosterior being lazy for MCMC that I mentioned above, but that's a narrow use case that will help multiprocessing.

**Comment by neerajprad** [comment]
Is everyone good with releasing a minor version with the current dev branch?
