### ISSUE TITLE
Clean up Distributions interface: docs, errors, refactoring

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#177]
This issues manages a sequence of PRs to refactor the `pyro.distributions.Distribution` interface.

- [x] #145 Document interface of `Distribution` base class
- [x] #145 Provide a default implementation of `Distribution.log_pdf` (as in #163 )
  Individual classes can still override this implementation, e.g. to add @martinjankowiak 's `log_pdf_mask` argument.
- [x] #191 Move documentation from [`distributions.rst`](https://github.com/uber/pyro/blob/dev/docs/source/distributions.rst) into `Distribution.__doc__` (as suggested by @dustinvtran in #145)
- [x] #294 Mark `@abstractmethod`s in `Distribution` base class
- [ ] #303 - Reporting errors in `batch_log_pdf` dimensional mismatch

Update all primitive distributions: add documentation, error checking, and assertions:
- [x] `Bernoulli`
- [x] `Beta`
- [x] `Categorical`
- [x] `Cauchy` - #302
- [x] #163 `Dirichlet`
- [x] `Delta` - #321
- [x] `DiagNormal`: rename to `Normal` #159 ?
- [x] `Exponential`
- [x] `Gamma`
- [x] `HalfCauchy`: replace `mean` with `lower bound`, add to sphinx
- [x] `LogNormal`
- [x] `Multinomial`: fix scorer - #301
- [x] `Normal`: rename to `MultivariateNormal` #159 ?  Removed in #355 
- [x] `NormalChol`: rename to `MultivariateNormalChol` #159 ? Removed in #355 
- [ ] `TransformedDistribution`
- [x] `Poisson`
- [x] `Uniform`

Feel free to revise this plan.
