### ISSUE TITLE
Reinstate Metropolis Hastings algorithm

### ISSUE THREAD

**Issue by neerajprad** [pyro-ppl/pyro#179]
@eb8680 had an implementation for single site Metropolis Hastings in #61. Let us resolve the issues raised in the PR, and reinstate the algorithm. This is also needed to build other algorithms like Annealed Importance Sampling. We could use this to develop the machinery for testing inference algorithms and distributions, as mentioned in Roger Grosse's [paper](https://papers.nips.cc/paper/6290-measuring-the-reliability-of-mcmc-inference-with-bidirectional-monte-carlo.pdf) on bidirectional MCMC.
 - [ ] Abstract TraceKernel class from which MCMC kernels will inherit #44 
 - [ ] Allow for strict replay behavior in Replay poutine #180 
 - [ ] Reinstate #61 (addressing the issues raised).
 - [ ] Test MH on some simple examples - from Bayesian data analysis (Gelman, A.), webPPL.

**Comment by neerajprad** [comment]
@OptimusLime - Assigning to you since you already have a draft out. Feel free to adjust the sub-tasks.
