### ISSUE TITLE
[FR] Contrib module for analyzing tabular data

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#1824]
This issue proposes a pyro.contrib.tabular module for analyzing heterogeneous tabular data with missing cells.

The particular latent variable model I'm interested in is [TreeCat](https://github.com/posterior/treecat), which supports pluggable models for different feature types (e.g. real, boolean, categorical, count, date, lat_long). However, once these feature models are implemented, it should be easy to implement additional latent variable models including [CrossCat](http://jmlr.org/papers/v17/11-392.html), various [latent tree models](https://arxiv.org/abs/1402.0577), [TreeGauss](https://arxiv.org/abs/1901.08770) (using the [Funsor](https://github.com/pyro-ppl/funsor) backend), and various models using normalizing flows. Ideally we can set up enough models to compare performance across a variety of datasets.

## Tasks
- [x] #1821 Add a `SpanningTree` distribution.
- [ ] #1370 Implement a `TreeCat` model and inference.
- [ ] #1370 Add example: [Boston housing](http://edwardlib.org/api/observations/boston_housing) (506 rows x 14 cols, real+binary)
- [ ] Add example: [US census 1990](https://archive.ics.uci.edu/ml/datasets/US+Census+Data+%281990%29) (2.5M rows x 68 cols, categorical)
- [ ] Support masked observe statement #1106
- [ ] Fix `infer_discrete` log_prob #1722 so `TreeCat` can be used as a guide
