### ISSUE TITLE
Poutine cleanup

### ISSUE THREAD

**Issue by eb8680** [pyro-ppl/pyro#183]
Master issue for tracking pre-release Poutine cleanup.  Mostly factors into two distinct major tasks plus some extra cleanup.

First major task: Poutine architecture finalization (#201): have to be done together
- [x] Return type invariance: don't change function return type; put in property instead (e.g. `TracePoutine`)
- [x] Poutines as context managers: `_enter_poutine`/`_exit_poutine` -> `__enter__`/`__exit__`
- [x] Move `_push_stack`/`_pop_stack` inside `__enter__`/`__exit__`
- [x] Clear, explicit execution model
- [x] Consistent use of variables in message and arguments outside - maybe remove args from `_pyro_*` methods and rely only on message
- [x] Remove superfluous inner functions in `pyro/poutine/__init__.py` definitions

Second major task: Unifying `msg`, `Trace`, and `TraceGraph` (#234): will also have to be done together
- [x] Collapse `TracePoutine` and `TraceGraphPoutine` into a single class
- [x] Unify `Trace` and `TraceGraph` data structures, make custom `Site` type
- [x] Unify message (in `apply_stack`) and new `Site` type

Unifying `sample` and `observe` (#254):
- [x] Unify `sample` and `observe` sites and `_pyro_sample`/`_pyro_observe` Poutine logic #29 

Documentation (mostly #201):
- [x] Clear, detailed docstrings for all poutine classes and methods and aliases
- [x] Explanatory comments throughout the internal code

Other cleanup:
- [x] Remove `poutine.cache` if unable to justify with use case (done in #201 due to maintenance difficulty)
- [x] Promote `do` and `condition` to top-level functions #94 
- [x] Fully implement `map_data` in terms of `irange`/`iarange` as in #184
