### ISSUE TITLE
Drop support for Python 2 (a checklist)

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#1963]
Follows #1935 

I've attempted to prioritize these:

- [x] #1962 Remove Python 2 from ci test grid.
- [x] #1965 Remove dependency on `six`:
    - replace`six.moves.reduce` with `functools.reduce`.
    - ...
- [x] #1967 Replace contextlib2 with contextlib
- [x] #1967 Remove `from __future__ import ...` headers.
- [x] #1972 Remove py2 installation from [docs](http://docs.pyro.ai/en/stable/installation.html) and readme
- [x] #1972 Change dockerfile python versions.
- [x] #1962 Remove Python 2 from setup.py.
- ...others?

### Triaged

- Replace `super(MyClass, self)` -> `super()` in most cases?
- Modernize `six.reraise` logic to clean up error messages.
     Currently error messages look good in Python2 but give duplicate stack traces in Python3.

**Comment by neerajprad** [comment]
> six.moves.reduce is used often

I think we can just use `functools.reduce` in python 3.

**Comment by jpchen** [comment]
> Currently error messages look good in Python2 but give duplicate stack traces in Python3.

this seems to be a consequence of pytest exception handling, not `six`.  will investigate further but this may be separate from the migration.
