### ISSUE TITLE
Add a contrib.timeseries module

### ISSUE THREAD

**Issue by martinjankowiak** [pyro-ppl/pyro#2090]
- [x] matern kernels as state space models #2077 
- [x] basic univariate GP model and base class for `TimeSeriesModel`s #2088
- [x] add example usage for a contrib.timeseries model #2092 
- [x] add `LinearlyCoupledMaternGP' #2094 
- [x] add 'GenericLGSSM` #2099 
- [x] add 'GenericLGSSMWithGPNoiseModel' #2100 
- [x] add `DependentMaternGP` #2107 
- [x] decorate with `torch.no_grad()` where appropriate #2106 
- [x] add support for nu=0.5 #2106
- [x] add `LinearlyCoupledDependentMaternGP` #2112 
- [x] refactor to use `PyroModule` #2142 
- ~~add support for observation (noise) models~~
- ~~do an optimization pass (use `scale_tril` where appropriate, etc.)~~
- ~~make use of recently added constraints technology as in #2104~~
