### ISSUE TITLE
[FR] Automatic reparameterization

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#2221]
Could we implement automatic reparameterization? Maybe at least for autoguides?

A good test example would be Neal's funnel, as described in the paper.

See Gorinova, Moore, and Hoffman (2019)
https://arxiv.org/pdf/1906.03028.pdf

## Tasks
- [x] #2222 implement `poutine.param` and basic framework
- [x] #2235 generalize `LocScaleTransform` and implement an effect `pyro.infer.reparam.decenter()`
- [x] #2235 implement `TransformReparameterizer` (suggested by @fehiepsi ) ~~and an effect `pyro.infer.reparam.neutra()`~~
- [x] #2235 support `Independent` distributions
- ~~implement a Levy-Ito reparameterization~~
- ~~implement a `difference` or `cumsum` reparameterization for time series~~
- [ ] #2252 implement a Fourier transform reparameterization for time series

**Comment by fehiepsi** [comment]
FYI, numpyro supports automatic reparameterization for both autoguide and
mcmc by defining that distribution as a transformed distribution. This is a
nice feature to have and can help for avoiding mistakes where support of
some “transformed” distributions depend on other variable, e.g. Uniform(0,
a) has dynamic support but currently autoguide will use a fixed transform
(depending on initial value of a). If we reparameterize here, we only need
to learn guide for U(0, 1) and that issue won’t happen.

However, the biggest problem for supporting this is non-trivial codes will
be added, so it is hard to review and follow the logic regarding this
feature in NumPyro. I will sketch the solution there below so we can
discuss if there is a better solution.
