### ISSUE TITLE
Switch from MIT license to Apache-2.0 license

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#2249]
As part of Pyro's move from Uber to the Linux Foundation, we are replacing the existing
> MIT license + Contributor License Agreement

with a simpler structure:

> Apache 2.0 license + no CLA

## Tasks

- [x] #2250 Include copyright notices on each file: `Copyright (c) 2017-2019 Uber Technologies, Inc.`
- [x] #2250 Include an SPDX short-form identifier in a comment at the top of each file in the repo, wherever reasonably possible. (addresses #2067 )
- [x] #2250 Switch from MIT to Apache-2.0 license
- [x] Disable Uber CLA

**Comment by swinslow** [comment]
Hi @fritzo, on the SPDX identifiers, https://spdx.org/ids has more details about this (or I'm happy to weigh in if you have questions!)

On the copyright notices, another option that some of our projects have gone with has been to use a more general form of copyright notice, such as: "Copyright Contributors to the Pyro project." We actually just posted a blog about this [earlier today](https://www.linuxfoundation.org/blog/2020/01/copyright-notices-in-open-source-software-projects/) — noting it here in case Pyro wants to take a similar approach.

**Comment by fritzo** [comment]
Thanks, @swinslow, can I include this line in each source file?
> Copyright (c)  2017-2018 Contributors to the Pyro project.

**Comment by swinslow** [comment]
From the LF's perspective, I think that would be fine, though a couple of comments:

* You might consider omitting the years range. Including it tends to result in questions about e.g. "when do we need to update it in each file?" or "what if contributions were made in 2019 but it's not in the year range?" Because of those sorts of things, we've increasingly seen (and recommended) that projects may just omit year ranges.

* Similarly with the (c) symbol — fine to include if you like and no harm in doing so, though we've seen some projects omit it. Mostly because omitting it helps avoid the question of whether e.g. redistributions need to include multiple different lines in attribution notices, when different variations on that symbol inevitably appear — e.g. `(c)` vs. `(C)` vs. `Ⓒ` vs. `&copy;` vs...

* Lastly, just to note, you may also want to check with your own legal counsel about whether they have a preference for the notice format, since in any event you / they will be retaining ownership of the copyrights (no matter what notice you put on it!) I'm not able to provide you with legal advice on this, unfortunately — just trying to be transparent on that  :)
