### ISSUE TITLE
Reparametrization trick is incorrect in presence of discontinuity

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#2277]
This issue was raised by @hongseok-yang.

In models where likelihoods discontinuously depend on a latent variable, it is incorrect to use the parameterization trick for that variable in the guide. A correct workaround is to substitute the guide distribution with a non-reparameterized copy. For example:
```diff
  def model(data):
      z = pyro.sample("z", dist.Normal(0,1))
      p = z.round().clamp(min=0.2, max=0.8)
      pyro.sample("x", dist.Bernoulli(p), obs=tensor(0.))

  def guide(data):
      loc = pyro.param("loc", torch.tensor(0.))
      scale = pyro.param("scale", torch.tensor(1.), constraint=positive)
-    z = pyro.sample("z", dist.Normal(loc, 1))
+    z = pyro.sample("z", NonreparameterizedNormal(loc, 1))
```

## Tasks
- [ ] allow manual user-specified disabling of the reparameterization trick for a single variable.
- [ ] add validation logic to detect when the issue occurs
- [ ] add a tutorial on "caveats of variational inference"
