### ISSUE TITLE
miscellaneous pre-launch cleanup

### ISSUE THREAD

**Issue by martinjankowiak** [pyro-ppl/pyro#228]
- [x] #344 make sure all py2/py3 compatibility issues are dealt with cleanly (probably: use `six` everywhere) 
- [x] add all Pyro classes to the sphinx documentation
- [x] #472 sane importing strategy and default imports
  (What does this mean?)
- [x] clean up module namespaces, especially global namespace
- [x] #394 Configure `yapf` and try running it
- [x] #408 Configure `isort` and try running it
- [x] Populate `README.md`
- [x] Clean up `CONTRIBUTING.md`
- [x] Write installation guide (website)
- [x] Populate [link] placeholders in docs
- [x] Clean up wikis/move content out of public repo
- [x] Clean up or remove old git branches.
  Find yours at https://github.com/uber/pyro/branches/yours
  (Please ask branch owners before deleting branches that are not yours)
- [x] Remove any stray `pdb` imports or commented-out `set_trace`s (e.g. in `tracegraph_elbo.py`)
  (You can do this regularly by installing [silver searcher](https://github.com/ggreer/the_silver_searcher#installing) and running `ag pdb`)

add various other little miscellaneous tasks here

## Triaged
- [ ] Add a `CODE_OF_CONDUCT.md`
- [ ] Make sure writing style is uniform across all docs
- [ ] put package on pypi 
- [ ] break up utils into module-specific utils
