### ISSUE TITLE
Add a contrib.forecasting module

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#2311]
Related to #2090 but focused on a narrow class of models, inference methods, and forecasting queries. See [design doc](https://docs.google.com/document/d/1jqQ_7mCnggqqmICzux2Fr9yvHO5AoVpBdmjNC0i6JAY).

- [x] #2309 implement a `GaussianHMM.prefix_condition()` method
- [x] #2309 implement a `PrefixReplayMessenger`
- [x] #2309 create a `ForecastingModel` base class and `Forecaster` wrapper
- [x] #2309 support Stable, StudentT, LinearHMM reparameterization
- [x] #2312 expose `.get_dist()` method of contrib.timeseries models
- [x] #2313 add seasonality helpers
- [x] #2335 add more seasonality helpers
- [x] #2316 add an eval/backtesting module
- [x] #2318 add a simple example
- [x] #2320 support `DiscreteCosineReparam` over `time_plate`, or support DCT in the guide
- [x] #2323 support subsampling in `AutoNormal`
- [x] #2330 support warm-starting in `backtest()`
- [x] #2331 support more likelihood distributions
- [x] #2332 add duration kwargs to `GaussianHMM`s in contrib.timeseries
- [x] #2334 support independent `GaussianHMM`s via `IndependentHMM` wrapper
- [x] #2339 add a univariate tutorial
- [x] #2343 add a state space model tutorial
- [x] #2348 add a multivariate tutorial
- [x] initial release
