### ISSUE TITLE
pyro.distributions should not depend on pyro.anything_else

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#268]
`pyro.distributions` currently depends on a few helpers in `pyro.util`. We'll need to move these helpers into `pyro.distributions` before we can move `pyro.distributions` upstream.

- [x] #270 Move `pyro.util.log_gamma` to `pyro.distributions.util`
- [x] #270 Move `pyro.util.log_beta` to `pyro.distributions.util`
- [x] #270 Move `pyro.util.to_one_hot` to `pyro.distributions.util`
- TRIAGED Make `tests/distributions` independent of `tests/common.py`
