### ISSUE TITLE
Upgrade to PyTorch 1.8

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#2754]
This documents our upgrade plan to PyTorch 1.8, which breaks `pyro.distributions` as in Pyro 1.5.1 release. PyTorch 1.8.0 release is scheduled for sometime in March 2021.

## Plan

- [x] #2755 Release Pyro 1.5.2 which constrains to `torch<=1.7.2`.
- [x] #2757 Upgrade dev branch to PyTorch 1.7.0, fixing tests.
- [x] #2753 Pin Pyro dev branch to PyTorch nightly build, and fix many breaking changes.
- [x] #2739 Implement `Distribution.infer_shapes()`.
- ...
- [ ] After PyTorch 1.8 release, pin Pyro dev back to PyTorch release and release Pyro 1.6.

cc @neerajprad
