### ISSUE TITLE
FR make Reparam objects nn.Modules for jitting, saving, etc.

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#2831]
As we move away from the global param store and towards closer integration with `torch.nn.Module`s, it would be good to refactor `Reparam` objects to be `nn.Module`s.

## Design questions

- [ ] Can we preserve backwards compatibility?
- [ ] Would a `class Reparam(nn.Module)` be jittable, even though its `.forward()` method inputs non-tensors, e.g. distributions?

## Tasks

- [ ] make `Reparam` objects `nn.Module`s
- [ ] replace `Reparam.__call__()` with `.forward()`
- [ ] replace `pyro.param` statements in `Reparam` objects with `getattr(self, -)` or `setattr(self, -, PyroParam(-))`
