### ISSUE TITLE
Add Cuda tests

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#296]
See also #202 
See discussion in #284 

## Tasks
- [x] #297 `tests/distributions/`
- [x] #319 `tests/poutine/test_map_data.py`
- [x] #304 Add discovery of examples that support `--cuda` in `tests/test_examples.py`
- [x] #338 Add `Makefile` target to run unit tests with default tensor type as cuda

Add a `--cuda` flag to each example script:
- [x] #343 `examples/air/main.py`
- [x] #305 `examples/bayesian_regression.py`
- [x] `examples/dmm/dmm.py`
- [x] #107 `examples/ss-vae/example.py`
- [x] #340 `examples/vae.py`
