### ISSUE TITLE
Pyro 1.8 release checklist

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#2968]
- [ ] Quick start tutorial
- [ ] High-dimensional Bayesian workflow tutorial (@fritzo)
- [ ] #2967
- [ ] #2964 
- [ ] #2963 
- [ ] #2946 
- [ ] Pyro-compatibility shim for pyro.contrib.funsor (@eb8680)
